services:
  gitlab:
    container_name: ${GITLAB_CONTAINER_NAME}
    image: ${GITLAB_IMAGE_NAME}:${GITLAB_IMAGE_VERSION}
    restart: ${RESTART_POLICY}
    environment:
      - GITLAB_OMNIBUS_CONFIG="external_url 'http://gitlab.example.com';"
      - TZ=${TIMEZONE}
    ports:
      - ${GITLAB_HTTP_PORT}:80
      - ${GITLAB_HTTPS_PORT}:443
      - ${GITLAB_SSH_PORT}:22
    volumes:
      - gitlab_data:/var/opt/gitlab
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
    networks:
      - default
    depends_on: []
    shm_size: '256m'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}

networks:
  default:
    name: ${GITLAB_CONTAINER_NAME}_network
    driver: bridge

volumes:
  gitlab_data:
    name: ${GITLAB_CONTAINER_NAME}_data
    driver: local
  gitlab_config:
    name: ${GITLAB_CONTAINER_NAME}_config
    driver: local
  gitlab_logs:
    name: ${GITLAB_CONTAINER_NAME}_logs
    driver: local