version: '3.9'
services:      
  app:
    image: gitlab/gitlab-ee:latest
    container_name: gitlab
    restart: always
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
      - ${SSH_PORT}:22
    networks:
      - default
    volumes:
      - data:/var/opt/gitlab
      - ./data:/var/opt/gitlab 
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab   
    shm_size: '256m'

networks:
  default:
    name: docker_gitlab_network
    driver: bridge

volumes:
  data:
    name: docker_gitlab_data
    driver: local